# Generated by Django 4.1.10 on 2023-08-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='user_response',
        ),
    ]
